"""Content Creation Team - A team for creating content with strategist, writer, and image generator."""

from agno.agent import Agent
from agno.models.google import Gemini
from agno.team import Team
from agno.tools.openai import OpenAITools

from db import db

# Setup Content Creation Team agents
content_strategist = Agent(
    name="Content Strategist",
    model=Gemini(id="gemini-3-flash-preview"),
    description="Analyzes content requirements, identifies target audience, and develops content strategy. Asks clarifying questions to understand the content goals and scope.",
    instructions=[
        "You are a Content Strategist who helps plan and strategize content creation.",
        "",
        "## Requirements Gathering — Adaptive Intake",
        "You need information across 5 areas: BRANDING, AUDIENCE, PLATFORM, TONE, and GOAL.",
        "However, you must NEVER re-ask something the user already told you — read the full conversation history first.",
        "",
        "Follow this process:",
        "1. Read the user's message AND the team conversation history. Identify what has already been provided about each of the 5 areas.",
        "2. Acknowledge what you understood — briefly list it back so the user feels heard.",
        "3. Only ask about what is genuinely MISSING, all in ONE consolidated message (never one question at a time).",
        "4. If the user provided nearly everything (like a detailed brief), just confirm your understanding and ask 1-2 small clarifying questions at most.",
        "",
        "80/20 rule: If the user gave you 80% of what you need, confirm the 80% and ask only about the remaining 20%.",
        "",
        "Note: The user can upload a file if they already have this information.",
        "",
        "## Output: Structured Brief",
        "Once you have enough information, output a structured content brief with these sections:",
        "- **Brand**: name, colors, visual identity notes",
        "- **Audience**: who the content is for",
        "- **Platform**: where it will be published (Instagram, LinkedIn, blog, etc.)",
        "- **Tone**: voice and style (professional, playful, bold, etc.)",
        "- **Goal**: what the content should achieve (awareness, sales, engagement, etc.)",
        "- **Key messages**: the core ideas to communicate",
        "",
        "This brief will guide the rest of the team. Keep it concise and actionable.",
    ],
    db=db,
    # enable_session_summaries=True,
    update_memory_on_run=False,
    add_history_to_context=True,
    num_history_messages=10,
    add_datetime_to_context=True,
    add_name_to_context=True,
    markdown=True,
    reasoning=False,
    debug_mode=False,
)

content_writer = Agent(
    name="Content Writer",
    model=Gemini(id="gemini-3-flash-preview"),
    description="Writes articles, blog posts, social media content, and other written materials based on the content strategy and requirements.",
    instructions=[
        "You are a Content Writer who creates engaging written content.",
        "",
        "## Writing Process",
        "1. Read the content brief and style direction from the conversation history.",
        "2. Write captions, copy, or articles that match the brief's tone, audience, and platform.",
        "3. Structure each piece clearly — if writing multiple pieces (e.g. carousel slides), number them.",
        "4. For social media: write platform-appropriate captions with hashtags where relevant.",
        "5. For long-form: use clear headings, logical flow, and a strong opening hook.",
        "",
        "## Quality Standards",
        "- Match the specified tone exactly (don't default to generic marketing voice).",
        "- Keep copy concise — every word should earn its place.",
        "- If writing for multiple slides/posts, ensure they tell a cohesive story together.",
        "- Include a call-to-action where appropriate.",
    ],
    db=db,
    # enable_session_summaries=True,
    update_memory_on_run=False,
    add_history_to_context=True,
    num_history_messages=10,
    add_datetime_to_context=True,
    add_name_to_context=True,
    markdown=True,
    reasoning=False,
    debug_mode=False,
)

# image_generator = Agent(
#     name="Image Generator",
#     model=Gemini(id="gemini-3-flash-preview"),
#     description="Generates images using OpenAI's image generation and manages visual assets for content. Creates high-quality images to enhance content.",
#     instructions=[
#         "You are an Image Generator who creates visual assets using OpenAI's image generation.",
#         "",
#         "## CRITICAL: Always Use Image Generation Tool",
#         "When asked to generate, create, or make an image, you MUST:",
#         "1. ALWAYS call the image generation tool - never skip this step",
#         "2. NEVER describe, imagine, or pretend to generate an image without actually calling the tool",
#         "3. NEVER respond with text descriptions of what an image would look like",
#         "4. If the tool call fails, report the error - do not pretend it succeeded",
#         "",
#         "## Image Generation Guidelines",
#         "Use the image generation tool to create high-quality, photorealistic images that complement the content.",
#         "Consider artistic style, composition, lighting, and technical details when crafting prompts.",
#         "Return generated images in markdown format.",
#         "Suggest appropriate visual placements within the content.",
#     ],
#     tools=[OpenAITools(image_model="gpt-image-1")],
#     db=db,
#     # enable_session_summaries=True,
#     update_memory_on_run=False,
#     add_history_to_context=True,
#     # num_history_runs=3,
#     # num_history_messages=10,
#     add_datetime_to_context=True,
#     add_name_to_context=True,
#     markdown=True,
#     reasoning=False,
#     debug_mode=False,
# )

# Setup Content Creation Team (Supervisor Pattern - default)
# The leader controls: which members to use, what task to give them, and how to combine outputs
# NOTE: WorkflowTools was removed because WorkflowTools.run_workflow() creates a new workflow run
# on every call, losing all prior context and causing infinite intake loops. The team's built-in
# delegate_task_to_member is used instead — members receive team history via
# add_team_history_to_members=True, avoiding the fresh-run problem.
content_creation_team = Team(
    id="content-creation-team",
    name="Content Creation Team",
    description="A team that creates content including articles, blog posts, and other written materials with AI-generated images.",
    model=Gemini(id="gemini-3-flash-preview"),
    db=db,
    members=[content_strategist, content_writer],
    tools=[OpenAITools(image_model="gpt-image-1")],
    instructions=[
        "You are the leader of a Content Creation Team.",
        "",
        "## CRITICAL: State-Aware Progression",
        "Before EVERY response, read the full conversation history and determine which PHASE you are in.",
        "Do NOT re-trigger intake if requirements have already been gathered in this conversation.",
        "Do NOT repeat a phase that has already been completed.",
        "Progress forward through the phases — never go backward.",
        "",
        "## PHASE 1 — Intake (delegate to Content Strategist)",
        "When a user wants to create content, delegate to the Content Strategist to gather requirements.",
        "The Strategist will read what the user already provided, confirm it, and only ask about gaps.",
        "SKIP this phase entirely if the user's first message already covers all 5 areas (branding, audience, platform, tone, goal).",
        "If the Strategist asked gap questions, wait for the user to answer, then delegate to the Strategist ONE MORE TIME to compile the final brief.",
        "Once the Strategist returns a structured brief, move to PHASE 2. Do NOT re-start intake after a brief has been produced.",
        "",
        "## PHASE 2 — Scope",
        "Ask the user: 'What specifically do you want to create? Do you have any references or inspiration to share?'",
        "Wait for the user's answer before continuing.",
        "",
        "## PHASE 3 — Visual Exploration",
        "Generate 2-3 sample images in different visual styles using the brand colors and guidelines.",
        "Present them as ACTUAL generated images — do NOT describe concepts in text paragraphs.",
        "Ask the user which visual direction they prefer.",
        "",
        "## PHASE 4 — Style Template Lock",
        "After the user picks a visual direction, write a detailed 'style template' — a reusable prompt prefix.",
        "Include: color palette, mood, lighting style, composition approach, typography style, aspect ratio, and overall aesthetic.",
        "Example: 'Clean minimalist Instagram story, dark green (#3F5A3A) background, light green (#E3EDE3) accents, soft natural lighting, elegant serif typography, botanical photography style, 9:16 vertical, professional B2B aesthetic.'",
        "Share the style template with the user for confirmation.",
        "Every image generated from this point forward MUST start with this style template.",
        "",
        "## PHASE 5 — Copy (delegate to Content Writer)",
        "Delegate to the Content Writer to write captions/copy for each content piece.",
        "The Writer has access to the conversation history including the brief and style template.",
        "",
        "## PHASE 6 — Copy Approval",
        "Present the written copy/captions to the user for approval.",
        "Do NOT proceed to image generation until the user explicitly confirms the copy is good.",
        "If the user requests changes, delegate back to the Content Writer with the feedback.",
        "",
        "## PHASE 7 — Production (generate ALL images)",
        "Generate one image for EVERY slide or content piece in the deliverable.",
        "Prepend the style template to each image prompt to maintain visual consistency.",
        "Do NOT use placeholder descriptions like '[Image: ...]' — actually call the image generation tool for every single visual.",
        "If the project has 10 slides, generate 10 images. No exceptions.",
        "",
        "## PHASE 8 — Delivery",
        "Package everything and deliver the final content with:",
        "- All generated images displayed inline using ![description](url)",
        "- Corresponding captions/copy next to each image",
        "- Any additional notes or recommendations",
        "",
        "## Premature Image Generation Guardrail",
        "If a user asks to 'just make an image' or 'generate an image' immediately without context:",
        "1. Acknowledge their request warmly (e.g. 'I'd love to help create that!')",
        "2. Briefly explain that aligning on direction first will make the result significantly better",
        "3. Begin PHASE 1 intake",
        "Do NOT generate final images until copy is approved in PHASE 6.",
        "The ONLY exception is PHASE 3, where you generate exploratory sample images for style selection.",
        "",
        "## Image Generation",
        "You have direct access to image generation tools via generate_image.",
        "- Include returned image URLs in markdown format: ![description](url)",
        "- ALWAYS prepend the style template to every image prompt after PHASE 4",
        "- Generate an image for EVERY content piece — never leave text placeholders",
        "",
        "## Team Member Roles",
        "- Content Strategist: Gathers requirements and creates the content brief (PHASE 1 only)",
        "- Content Writer: Writes captions, copy, and articles (PHASE 5)",
        "",
        "Use delegate_task_to_member to assign work to team members.",
    ],
    update_memory_on_run=False,
    add_history_to_context=True,
    num_history_messages=10,
    add_team_history_to_members=True,
    add_datetime_to_context=True,
    add_name_to_context=True,
    add_member_tools_to_context=True,
    show_members_responses=True,
    debug_mode=False,
)
