"""Indeed XML Feed tools for direct employers.

Indeed's Job Sync API is for ATS partners only (requires 6-week onboarding).
Direct employers like Pad Thai Padel should use the Indeed XML Feed:
- Free, no API key required
- Indeed crawls the feed automatically once the URL is registered
- Jobs appear on Indeed Thailand within 24-48 hours of the feed updating

## Setup (one time)
1. Submit your feed URL to Indeed at:
   https://employers.indeed.com/jobs/feed-submit
2. Indeed will crawl it automatically whenever jobs are added/updated

## Feed URL
The feed is served at: GET /indeed-feed.xml
(auto-generated by this server from the jobs stored in memory/DB)
"""

from __future__ import annotations

import json
import xml.etree.ElementTree as ET
from datetime import datetime, timezone
from typing import Optional

from agno.tools import Toolkit


class IndeedXMLFeedTools(Toolkit):
    """Tools for managing an Indeed XML job feed for direct employers.

    The feed is stored in-memory and served at /indeed-feed.xml.
    Register the feed URL once at https://employers.indeed.com/jobs/feed-submit
    and Indeed will auto-crawl it whenever it updates.
    """

    def __init__(self, base_url: str = ""):
        super().__init__(name="indeed_xml_feed_tools")
        self.base_url = base_url.rstrip("/")
        self._jobs: list[dict] = []  # in-memory store; swap for DB in Phase 2
        self.register(self.add_job_to_feed)
        self.register(self.list_feed_jobs)
        self.register(self.remove_job_from_feed)
        self.register(self.get_feed_url)
        self.register(self.generate_xml_feed)

    # ------------------------------------------------------------------
    # Public tools
    # ------------------------------------------------------------------

    def add_job_to_feed(
        self,
        title: str,
        description: str,
        company: str,
        location: str,
        job_type: str = "Full-time",
        salary: Optional[str] = None,
        apply_url: Optional[str] = None,
        apply_email: Optional[str] = None,
        reference_number: Optional[str] = None,
    ) -> str:
        """Add a new job to the Indeed XML feed.

        Args:
            title: Job title (e.g. "Padel Coach")
            description: Full job description (plain text or simple HTML)
            company: Company name (e.g. "Pad Thai Padel")
            location: Job location (e.g. "Bangkok, Thailand")
            job_type: Full-time / Part-time / Contract / Internship
            salary: Salary range as text (e.g. "30,000 - 40,000 THB/month")
            apply_url: URL where candidates apply (overrides email)
            apply_email: Email for applications
            reference_number: Your internal job reference code

        Returns:
            JSON string confirming the job was added and the feed URL.
        """
        import uuid
        job_id = reference_number or str(uuid.uuid4())[:8].upper()

        job = {
            "id": job_id,
            "title": title,
            "description": description,
            "company": company,
            "location": location,
            "job_type": job_type,
            "salary": salary,
            "apply_url": apply_url or (f"mailto:{apply_email}" if apply_email else None),
            "posted_at": datetime.now(timezone.utc).isoformat(),
        }
        self._jobs.append(job)

        feed_url = f"{self.base_url}/indeed-feed.xml" if self.base_url else "/indeed-feed.xml"

        return json.dumps({
            "success": True,
            "job_id": job_id,
            "message": f"Job '{title}' added to Indeed feed. Total jobs in feed: {len(self._jobs)}.",
            "feed_url": feed_url,
            "next_step": (
                "If this is your first job, register your feed URL with Indeed at: "
                "https://employers.indeed.com/jobs/feed-submit"
            ),
        })

    def list_feed_jobs(self) -> str:
        """List all jobs currently in the Indeed XML feed.

        Returns:
            JSON string with all active jobs in the feed.
        """
        return json.dumps({
            "success": True,
            "count": len(self._jobs),
            "jobs": [
                {
                    "id": j["id"],
                    "title": j["title"],
                    "location": j["location"],
                    "job_type": j["job_type"],
                    "posted_at": j["posted_at"],
                }
                for j in self._jobs
            ],
        })

    def remove_job_from_feed(self, job_id: str) -> str:
        """Remove a job from the Indeed XML feed (it will expire on Indeed within 24h).

        Args:
            job_id: The job reference ID to remove.

        Returns:
            JSON string confirming removal.
        """
        before = len(self._jobs)
        self._jobs = [j for j in self._jobs if j["id"] != job_id]
        removed = before - len(self._jobs)

        if removed:
            return json.dumps({"success": True, "message": f"Job {job_id} removed from feed."})
        return json.dumps({"success": False, "error": f"Job ID '{job_id}' not found in feed."})

    def get_feed_url(self) -> str:
        """Get the public URL for the Indeed XML feed to submit to Indeed.

        Returns:
            JSON string with feed URL and submission instructions.
        """
        feed_url = f"{self.base_url}/indeed-feed.xml" if self.base_url else "/indeed-feed.xml"
        return json.dumps({
            "feed_url": feed_url,
            "how_to_register": (
                "Go to https://employers.indeed.com/jobs/feed-submit and submit this URL. "
                "Indeed will crawl it within 24-48 hours and list your jobs automatically. "
                "You only need to register it ONCE — after that, Indeed crawls it automatically."
            ),
            "jobs_in_feed": len(self._jobs),
        })

    def generate_xml_feed(self) -> str:
        """Generate the raw XML content of the current Indeed feed (for debugging).

        Returns:
            The full XML string for the current feed.
        """
        return self._build_xml()

    # ------------------------------------------------------------------
    # Internal: XML generation
    # ------------------------------------------------------------------

    def _build_xml(self) -> str:
        """Build the Indeed-compliant XML feed string."""
        source = ET.Element("source")

        publisher = ET.SubElement(source, "publisher")
        publisher.text = self._jobs[0]["company"] if self._jobs else "Company"

        publish_date = ET.SubElement(source, "publishDate")
        publish_date.text = datetime.now(timezone.utc).strftime("%a, %d %b %Y %H:%M:%S +0000")

        for job in self._jobs:
            job_el = ET.SubElement(source, "job")

            title = ET.SubElement(job_el, "title")
            title.text = job["title"]

            date_posted = ET.SubElement(job_el, "date")
            date_posted.text = datetime.fromisoformat(job["posted_at"]).strftime(
                "%a, %d %b %Y %H:%M:%S +0000"
            )

            ref = ET.SubElement(job_el, "referencenumber")
            ref.text = job["id"]

            url = ET.SubElement(job_el, "url")
            url.text = job.get("apply_url") or f"{self.base_url}/jobs/{job['id']}"

            company = ET.SubElement(job_el, "company")
            company.text = job["company"]

            city_el = ET.SubElement(job_el, "city")
            state_el = ET.SubElement(job_el, "state")
            country_el = ET.SubElement(job_el, "country")
            # Parse location: "Bangkok, Thailand" → city=Bangkok, country=Thailand
            parts = [p.strip() for p in job["location"].split(",")]
            city_el.text = parts[0] if parts else job["location"]
            state_el.text = parts[1] if len(parts) > 1 else ""
            country_el.text = parts[-1] if len(parts) > 1 else "Thailand"

            desc = ET.SubElement(job_el, "description")
            desc.text = job["description"]

            job_type_el = ET.SubElement(job_el, "jobtype")
            job_type_el.text = job.get("job_type", "Full-time")

            if job.get("salary"):
                salary_el = ET.SubElement(job_el, "salary")
                salary_el.text = job["salary"]

        return ET.tostring(source, encoding="unicode", xml_declaration=True)
